
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import "/imports/plugins/core/checkout/server";
import "/imports/plugins/core/layout/server";
import "/imports/plugins/core/orders/server";
import "/imports/plugins/included/analytics/server";
import "/imports/plugins/included/authnet/server";
import "/imports/plugins/included/braintree/server";
import "/imports/plugins/included/example-paymentmethod/server";
import "/imports/plugins/included/inventory/server";
import "/imports/plugins/included/jobcontrol/server";
import "/imports/plugins/included/paypal/server";
import "/imports/plugins/included/shipping/server";
import "/imports/plugins/included/social/server";
import "/imports/plugins/included/stripe/server";
import "/imports/plugins/core/checkout/register.js";
import "/imports/plugins/core/dashboard/register.js";
import "/imports/plugins/core/layout/register.js";
import "/imports/plugins/core/orders/register.js";
import "/imports/plugins/core/ui/register.js";
import "/imports/plugins/core/ui-navbar/register.js";
import "/imports/plugins/core/ui-tagnav/register.js";
import "/imports/plugins/included/analytics/register.js";
import "/imports/plugins/included/authnet/register.js";
import "/imports/plugins/included/braintree/register.js";
import "/imports/plugins/included/default-theme/register.js";
import "/imports/plugins/included/example-paymentmethod/register.js";
import "/imports/plugins/included/inventory/register.js";
import "/imports/plugins/included/jobcontrol/register.js";
import "/imports/plugins/included/paypal/register.js";
import "/imports/plugins/included/product-variant/register.js";
import "/imports/plugins/included/shipping/register.js";
import "/imports/plugins/included/social/register.js";
import "/imports/plugins/included/stripe/register.js";
